-- CreateTable
CREATE TABLE "Client" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "contractDate" DATETIME,
    "policyYear" INTEGER,
    "fullName" TEXT NOT NULL,
    "ssn" TEXT,
    "birthDate" DATETIME,
    "email" TEXT,
    "phone" TEXT,
    "address" TEXT,
    "county" TEXT,
    "state" TEXT,
    "coverageType" TEXT,
    "insurer" TEXT,
    "affiliatesCount" INTEGER DEFAULT 1,
    "planName" TEXT,
    "planCategory" TEXT,
    "planId" TEXT,
    "acaPrice" REAL DEFAULT 0,
    "wnPolicy" TEXT,
    "wnPrice" REAL DEFAULT 0,
    "totalMonthly" REAL DEFAULT 0,
    "annualIncome" REAL,
    "status" TEXT DEFAULT 'Activo',
    "renewalDate" DATETIME,
    "preferredDoctor" TEXT,
    "specificMedication" TEXT,
    "authorizedMarket" TEXT,
    "bankHolder" TEXT,
    "bankName" TEXT,
    "bankRouting" TEXT,
    "bankAccount" TEXT,
    "bankAccountType" TEXT,
    "portalUser" TEXT,
    "portalPassword" TEXT,
    "googleReview" TEXT,
    "pendingDocs" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Dependent" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "clientId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "name" TEXT,
    "birthDate" DATETIME,
    CONSTRAINT "Dependent_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
